// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Name string `json:"name"`
}

type Product struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
